# Generated by Django 4.1.5 on 2023-02-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='responsibleID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roleLevel',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenanceDate', models.DateField()),
                ('maintenanceFile', models.FileField(upload_to='maintenance/')),
                ('testDate', models.DateField()),
                ('testFile', models.FileField(upload_to='car_test/')),
                ('mekifFile', models.FileField(upload_to='mekif/')),
                ('hovaFile', models.FileField(upload_to='hova/')),
                ('kilometer', models.IntegerField()),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cars')),
            ],
        ),
    ]
