# Generated by Django 4.1.5 on 2023-02-23 08:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_departments_responsibleid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shiftDate', models.DateField()),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cars')),
                ('maintenanceTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.maintenancetypes')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logDate', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cars')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drivings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('startKilometer', models.IntegerField()),
                ('endKilometer', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('startImg1', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('startImg2', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('startImg3', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('endImg1', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cars')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
