# Generated by Django 4.1.5 on 2023-02-24 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_maintenancetypes_shifts_logs_drivings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenance',
            name='hovaFile',
            field=models.FileField(max_length=200, upload_to='hova/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='maintenanceFile',
            field=models.FileField(max_length=200, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='mekifFile',
            field=models.FileField(max_length=200, upload_to='mekif/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='testFile',
            field=models.FileField(max_length=200, upload_to='car_test/'),
        ),
        migrations.AlterField(
            model_name='carorders',
            name='fromTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='carorders',
            name='toTime',
            field=models.TimeField(blank=True, default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.IntegerField(default=-1),
        ),
    ]
