# Generated by Django 4.1.5 on 2023-02-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_cars_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='department',
        ),
    ]
