# Generated by Django 4.1.5 on 2023-02-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_cars_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='department',
            new_name='department_id',
        ),
    ]
