# Generated by Django 4.1.5 on 2023-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_rename_department_cars_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
