# Generated by Django 4.1.5 on 2023-02-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0019_alter_customuser_id_alter_drivings_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realID', models.CharField(blank=True, max_length=10)),
                ('jobTitle', models.CharField(blank=True, max_length=50)),
                ('department', models.IntegerField(blank=True)),
                ('roleLevel', models.SmallIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realID', models.CharField(blank=True, max_length=10)),
                ('jobTitle', models.CharField(blank=True, max_length=50)),
                ('department', models.IntegerField(blank=True)),
                ('roleLevel', models.SmallIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='department_id',
            new_name='department',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
