# Generated by Django 4.1.5 on 2023-02-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_profile_profile1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
