# Generated by Django 4.1.5 on 2023-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorders',
            name='carImg',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
