# Generated by Django 4.1.5 on 2023-02-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_carorders_carimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmaintenance',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carorders',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carorders',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='drivings',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='drivings',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='logs',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='carID',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='maintenanceTypeID',
            new_name='maintenanceType',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='userID',
            new_name='user',
        ),
    ]
