# Generated by Django 4.1.5 on 2023-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_rename_carid_carmaintenance_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='files/images'),
        ),
    ]
