# Generated by Django 4.1.5 on 2023-02-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenance',
            name='hovaFile',
            field=models.FileField(blank=True, max_length=200, upload_to='hova/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='maintenanceFile',
            field=models.FileField(blank=True, max_length=200, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='mekifFile',
            field=models.FileField(blank=True, max_length=200, upload_to='mekif/'),
        ),
        migrations.AlterField(
            model_name='carmaintenance',
            name='testFile',
            field=models.FileField(blank=True, max_length=200, upload_to='car_test/'),
        ),
    ]
