# Generated by Django 4.1.5 on 2023-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_alter_carmaintenance_hovafile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenance',
            name='maintenanceFile',
            field=models.FileField(blank=True, max_length=200, upload_to='static/maintenance/'),
        ),
    ]
