# Generated by Django 4.1.5 on 2023-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_drivings_endimg2_drivings_endimg3'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorders',
            name='carName',
            field=models.CharField(default='make model', max_length=50),
            preserve_default=False,
        ),
    ]
