# Generated by Django 4.1.5 on 2023-03-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0038_alter_carorders_carname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmaintenance',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='carorders',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='carorders',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cars',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.departments'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logs',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='maintenanceType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.maintenancetypes'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
