# Generated by Django 4.1.5 on 2023-03-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_alter_carmaintenance_car_alter_carorders_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.departments'),
        ),
    ]
