# Generated by Django 4.1.5 on 2023-03-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorders',
            name='carName',
        ),
    ]
