# Generated by Django 4.1.5 on 2023-03-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0042_carorders_carname_remove_carmaintenance_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorders',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carorders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='department',
        ),
        migrations.AddField(
            model_name='carorders',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='carorders',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cars',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.departments'),
        ),
    ]
