# Generated by Django 4.1.5 on 2023-03-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_remove_carorders_car_remove_carorders_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorders',
            name='carName',
        ),
    ]
