# Generated by Django 4.1.5 on 2023-03-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0048_alter_carorders_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.departments'),
        ),
    ]
