# Generated by Django 4.1.5 on 2023-03-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0054_remove_carorders_car_remove_profile_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorders',
            name='cars_relation',
        ),
        migrations.AddField(
            model_name='carorders',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cars',
            field=models.ManyToManyField(through='cars.CarOrders', to='cars.cars'),
        ),
    ]
