# Generated by Django 4.1.5 on 2023-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0055_remove_carorders_cars_relation_carorders_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cars',
        ),
        migrations.AddField(
            model_name='carorders',
            name='cars',
            field=models.ManyToManyField(related_name='orders', to='cars.cars'),
        ),
    ]
