# Generated by Django 4.1.5 on 2023-03-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0056_remove_profile_cars_carorders_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorders',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='carorders',
            name='car',
        ),
        migrations.CreateModel(
            name='Car_Order_Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carorders')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='orders',
            field=models.ManyToManyField(through='cars.Car_Order_Connection', to='cars.carorders'),
        ),
        migrations.AddField(
            model_name='carorders',
            name='car',
            field=models.ManyToManyField(through='cars.Car_Order_Connection', to='cars.cars'),
        ),
    ]
