# Generated by Django 4.1.5 on 2023-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0057_remove_carorders_cars_remove_carorders_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_order_connection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
