# Generated by Django 4.1.5 on 2023-03-05 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0062_remove_carorders_carimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmaintenance',
            name='car',
        ),
        migrations.AlterField(
            model_name='carorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='drivings',
            name='car',
        ),
        migrations.RemoveField(
            model_name='drivings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='car',
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 20, 27, 32, 311477)),
        ),
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='car',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='maintenanceType',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='user',
        ),
        migrations.AddField(
            model_name='carmaintenance',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='drivings',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='drivings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logs',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifts',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='maintenanceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.maintenancetypes'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
