# Generated by Django 4.1.5 on 2023-03-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0064_alter_logs_logdate_alter_profile_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carorders",
            name="fromTime",
        ),
        migrations.RemoveField(
            model_name="carorders",
            name="toTime",
        ),
        migrations.AlterField(
            model_name="carorders",
            name="fromDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="carorders",
            name="toDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="logs",
            name="logDate",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 9, 14, 33, 19, 135702)
            ),
        ),
    ]
