# Generated by Django 4.1.5 on 2023-03-21 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0070_roles_alter_logs_logdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivings',
            name='fromTime',
        ),
        migrations.RemoveField(
            model_name='drivings',
            name='toTime',
        ),
        migrations.AlterField(
            model_name='drivings',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='endKilometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 50, 38, 201284)),
        ),
    ]
