# Generated by Django 4.1.5 on 2023-03-21 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0072_drivings_user_alter_logs_logdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivings',
            name='user',
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 14, 58, 47, 16922)),
        ),
    ]
