# Generated by Django 4.1.5 on 2023-03-22 09:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0073_remove_drivings_user_alter_logs_logdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 11, 32, 56, 791086)),
        ),
    ]
