# Generated by Django 4.1.5 on 2023-03-22 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0074_drivings_user_alter_logs_logdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivings',
            name='endImg1',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='endImg2',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='endImg3',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='startImg1',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='startImg2',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='startImg3',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 16, 18, 43, 597136)),
        ),
    ]
