# Generated by Django 4.1.5 on 2023-03-26 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0075_alter_drivings_endimg1_alter_drivings_endimg2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivings',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='drivings',
            name='startKilometer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 12, 2, 47, 453675)),
        ),
    ]
