# Generated by Django 4.1.5 on 2023-03-29 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0076_alter_drivings_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorders',
            name='ended',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='logDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 18, 21, 51, 62743)),
        ),
    ]
